# Generated by Django 4.0.2 on 2022-02-17 00:31

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_categoria', models.CharField(max_length=40, verbose_name='categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo Principal')),
                ('resumen', models.TextField(blank=True, max_length=300, null=True, verbose_name='Resumen')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Actualizacion')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blog/media/', verbose_name='')),
                ('Categorias', models.ManyToManyField(to='blog.categoria')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
