# Generated by Django 4.0.2 on 2022-02-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, verbose_name='Cattegoria.')),
            ],
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Titulo')),
                ('content', models.TextField(blank=True, max_length=300, null=True, verbose_name='Resumen.')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Actualizacion')),
                ('category', models.ManyToManyField(to='home.categorias')),
            ],
        ),
    ]
